project:
  type: website

website:
  title: "5500"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: review.qmd
        text: Lit Review
      - href: main.ipynb
        text: Linked List

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



