project:
  type: website

website:
  title: "Mastering CRM & Data Structures"
  navbar:
    left:
      - href: authors.qmd
        text: About Us
      - href: introduction.qmd 
      - href: litreview.qmd
        text: Literature Review
      - href: code.qmd
        text: Project Walkthrough

      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/hannah-hana-kim/DSAN-5500
    background: "#EB8A90"

format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    linkcolor: "#EB8A90"
    mainfont: Georgia
