---
title: "Literature Review"
bibliography: project_reference.bib
format: html
---

## The Data Behind CRM Systems

Customer relationship management, also known as CRM is a key component of a businesses success. CRM is a strategy that companies use in an attempt to manage relationships with previous, current and future customers. CRM helps businesses and companies streamline processes, build relationships, increase sales, improve customer survival as well as a wealth of other benefits.[@salesforce] One benefit that many do not think of is CRM’s impact on a country’s innovation and sustainability efforts. This literature review will highlight the necessity of technologically advanced CRM systems and how it impacts a company's competitiveness and how CRM can improve innovation for a company.

As companies get more and more complex, the importance of CRM heightens. CRM is needed to improve service quality and build upon relationships with customers in order to satisfy them to survive in a competitive environment. There are three categories of CRM technology - Operational, Analytical and Cooperational. Operational CRM is the process of communication with a customer from marketing and sale stage till after sales services and receiving feedback is entrusted to a person. Analytical CRM is the tools and techniques used to analyze obtained data from operational CRM. Finally, Cooperational CRM is how customers interact with the company. All three CRM technologies are crucial for the success of a company. For instance, operational CRM without analytical CRM would make no sense as the data would not be used to improve the overall customer experience leading to better performance. In order for a company to compete with others they must utilize all three of these technologies.[@tohidi_necessity_2012]

Another aspect CRM can improve is companies' innovativeness. “Customer knowledge management and innovation are the two key modern-firm drivers for a set of successful survival, growth, and development strategies, enhancing business efficiency, performance, and sustainable competitive advantage.”[@gil-gomez_customer_2020] Essentially, knowledge and innovation are inalienable and inseparable. Meaning that the more knowledge one obtains about their customers, the more they can innovate. Some people even consider CRM to be a sort of Green IT, oriented toward digital transformation and sustainable business model innovation.[@gil-gomez_customer_2020]

CRM systems are built on complex software solution systems like client server architecture. The choice of software structure for building CRM systems depends on factors such as organizational requirements, technical capabilities, scalability needs, and budget considerations. Each software structure has its own advantages and disadvantages and depends on a company's needs. For instance, a small startup would need a very basic architecture with only a couple of clients. 

Customer relationship management is extremely important when it comes to a company's success. CRM should not be overlooked as it has the power to improve many aspects of a business, whether the business is small or large. 
