---
title: DSAN5500 Final Project
---

### Question #3 Exploring Applications

**Exploration: Examining different applications of the data structure that make it helpful for particular fields**

**Topic Chosen:**

Customer Relationship Management Systems

**Identify a substantive application of that topic in a field you are interested in: e.g., bioinformatics, marketing, finance, NLP, image processing, operations management, social science:**

Marketing

**Write a Literature Review section containing a few examples of the use of the topic in your chosen field that are particularly interesting to you:**

You can find the literature review [here](litreview.qmd).

**Create a Quarto document or Jupyter notebook containing code that you wrote yourself which illustrates the application of the data structure or algorithm within your domain of interest, describing in your own words (through comments or Markdown text above/below the code) how the code works and what it does.**

Our data structure can be found [here](code.qmd).